### ISSUE TITLE
Can't get any intuitive completion to work

### ISSUE THREAD

**Issue by ronakg** [ajh17/VimCompletesMe#26] opened 2016-04-21 20:51 UTC
Most of the time, the word I'm looking to complete is at the end of the list. If I change the direction option, then the word is at top of the list but list navigation starts from bottom in that case. So in both the cases I either have to write more letters or hit tab multiple times to get to the word I want.

Is this possible to fix?

**Comment by ajh17** [comment] 2016-04-22 02:44
If it's at the bottom of the list, you can use shift-tab to reverse the navigation of the popup menu. So if you set the direction to 'n', you have to hit Shift-tab once to get to the bottom of the list if nothing is currently selected in the popup menu.

Does that make sense?

This behavior can always be improved.

**Comment by ronakg** [comment] 2016-04-22 02:47
Is it possible somehow to change this combination of `tab` and `direction`?

**Comment by ajh17** [comment] 2016-04-22 02:53
Definitely.

How do you want it to work though? Let's say you invoke the completion, and you want to start at the bottom, and then work your way up? 

Can you show an example of what the current behavior is versus what you would like it to be? 

Changing this behavior is pretty simple to do, so I'm just making sure what you would like the new behavior to be.

**Comment by ronakg** [comment] 2016-04-22 03:09
The default behavior of plugin is different from default behavior of vim's `C-x C-n` and `C-x C-p`.

For example, let's say I have 5 words, `item1`...`item5`.

If `C-x C-n` shows the list from 1 to 5 and navigates the list 1 to 5.
Whereas plugin shows the list 1 to 5, but navigates the list from 5 to 1.

I'm seeing some difference in the no of items in lists too. Plugin's list doesn't match with any of Vim's built-in completion commands, tried with `n`, `p`, `o` and `[`.

**Comment by ajh17** [comment] 2016-04-22 03:15
I guess I'm not seeing this problem. 

This is what I see using VimCompletesMe's tab at first, and then the built in Ctrl-X Ctrl-n:

https://asciinema.org/a/7qm03l8mb70poa0sjc48232cz

Are you getting something different?

For your second question, I'm not sure what you mean, are you talking about a VCM's configuration setting?

**Comment by ronakg** [comment] 2016-04-22 03:24
I tried the same thing and you're right. My example didn't work.

Looks like behavior is different when I'm using it in my project. I have a tags file, which must also be coming into picture for completion?

**Comment by ajh17** [comment] 2016-04-22 03:33
I just tried it with a tags file, and I'm still not able to reproduce your problem. Perhaps you have some plugin that would interfere in some way?

I'm also not seeing your second problem. VimCompleteMe's list is the same as the list returned by Ctrl-X-modes for me.

**Comment by ronakg** [comment] 2016-04-22 03:34
Okay. Let me do some more research into this. I'll let you know if I find something.

**Comment by ronakg** [comment] 2016-04-24 19:50
Changing the direction in preview window works better for me. Not sure about other cases, so I'll just keep it in my fork.

```vim
  if pumvisible()
      if a:shift_tab
          return dirs[dir]
      else
          return dirs[!dir]
      endif
  endif
```

**Comment by ajh17** [comment] 2016-04-24 21:16
Thanks. 

Seeing as I can't reproduce the problem, I'm closing this for now, but feel free to reopen it if you found a good reproducible case.

**Closed by ajh17** 2016-04-24 21:16 UTC
