### ISSUE TITLE
How does this plugin interact with snippet plugins like SnipMate?

### ISSUE THREAD

**Issue by ErichDonGubler** [ajh17/VimCompletesMe#41] opened 2017-03-27 13:08 UTC
One curiousity that keeps me from immediately trying this plugin is knowing how it will interact with other plugins I already rely on like SnipMate. Does this plugin require further configuration, or can I simply drop it in and expect it to work?

I can (and will!) do the homework myself, of course, but you might get some more users if you were to explain this up front. :)

Looking forward to trying this out!

**Comment by ajh17** [comment] 2017-03-31 04:24
Already documented in `doc/VimCompletesMe.txt` and Duplicate of #12. :)

**Closed by ajh17** 2017-03-31 04:24 UTC
