### ISSUE TITLE
Keyword completion starts at wrong end of menu after failed omni completion

### ISSUE THREAD

**Issue by pauloue** [ajh17/VimCompletesMe#65] opened 2019-07-31 23:32 UTC
In a c++ file, with `g:vcm_direction = 'n'`:
```
int foo;
std::<TAB><TAB>
bar
```
First tab tries and fails omni completion, second tab shows following menu:
```
bar
int
foo
std <-- selected
```
Third tab jump to the top and selects `bar`.

**Comment by ajh17** [comment] 2019-08-06 04:07
Duplicate of #7. See also: commit adecd7c4bf64099ddfd91d986b71c70889ff92e5.

**Comment by pauloue** [comment] 2019-08-10 19:29
This issue is specifically about keyword completion after failed omni completion. The bug described in the linked issue and FAQ entry seems to have been fixed by 9aa575cb756980395f1b03379fdb5b6138d68648.

I found the fix for this bug. This line:
https://github.com/ajh17/VimCompletesMe/blob/cc1eab38cca26fd1e387df5ce78e6f1e51aed8f4/autoload/VimCompletesMe.vim#L35
should be: `let exp = "\<C-x>" . dirs[!dir]`

(Why is `dirs[dir]` the opposite of `g:vcm_direction`?)

**Comment by ajh17** [comment] 2019-08-15 05:35
Try invoking Ctrl-X and Ctrl-n on `std::`. It will select "foo" even though it's AFTER your cursor. 

Usually, the word you want complete is located before the cursor. VCM is invoking Ctrl-X Ctrl-p and then using the forward direction when the popup menu is open. Thus, this is why you see "std" completed. Generally, you'd  go back up the list, not forward, if you want to complete words that appear before the cursor first.

But VCM is honoring the same direction as the completion which is why it's a bit confusing. Let me improve on this front.

**Comment by pauloue** [comment] 2019-08-16 04:55
> Try invoking Ctrl-X and Ctrl-n on std::. It will select "foo" even though it's AFTER your cursor.

Doing so completes "bar" for me, which I think is expected because Ctrl+n completes keywords after the cursor.

> VCM is invoking Ctrl-X Ctrl-p and then using the forward direction when the popup menu is open.

VCM is doing that after failed omni completion, but not for regular keyword completion. With the following:
```
bit
b<TAB>
baz
buz
```
the completion menu shows "baz", "buz", "bit". If `g:vcm_direction` is 'n', it starts with "baz" and moves down the list (forward in the file) and if `g:vcm_direction` is 'p', it starts with "bit" and moves up the list (backwards in the file). This is the behavior I would expect. I agree that searching backwards is more useful, which is why I use 'p'.

After failed omni completion (change the line with "b" to "b::") keyword completion starts with Ctrl-X Ctrl-N with `g:vcm_direction='p'` and it starts with Ctrl-X Ctrl-P with `g:vcm_direction='n'`, then reverts to the expected direction.

**Comment by ajh17** [comment] 2019-08-16 05:05
Right, I actually meant foo, not bar :) 

Yes, I get your point, I initially changed it for the default keyword completion but I wish I didn't. It moved the actual bug to the "p" direction now (since the popup menu completion is backwards). The forward completion behavior is worse too in my opinion, since It doesn't complete the words I want to complete that are just before my cursor position.

Once I get some time, I'll spend some time improving and cleaning up the behavior.

**Comment by pauloue** [comment] 2019-08-16 05:47
As far as I know there's no way to avoid the backwards popup menu if you want to search backwards. I didn't like the old behavior of searching backwards for the first match and then switching to forwards. So I'm happy with the current behavior with the direction set to 'p'. (Except that the backwards direction also applies to non-keyword completion where it should probably be hardcoded to forwards)

**Closed** 2019-10-08 03:44 UTC
